'use client';

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'ru';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Переводы
const translations = {
  en: {
    // Header
    'header.home': 'Home',
    'header.game': 'Game',
    'header.scene_generator': 'Scene Generator',
    'header.connect_wallet': 'Connect Wallet',
    'header.disconnect': 'Disconnect',
    'header.profile': 'Profile',
    'header.demo_mode': 'Demo Mode',
    'header.test_wallets': 'Test Wallets',
    
    // Scene Generator
    'scene.generator_title': 'Scene Generator',
    'scene.generator_description': 'Create pixel art scenes with textures and sprites',
    'scene.canvas': 'Canvas',
    'scene.controls': 'Controls',
    'scene.draw_mode': 'Draw Mode',
    'scene.texture_mode': 'Texture Mode',
    'scene.sprite_mode': 'Sprite Mode',
    'scene.select_texture': 'Select Texture',
    'scene.select_sprite': 'Select Sprite',
    'scene.brush_size': 'Brush Size',
    'scene.water_mode': 'Water Mode',
    'scene.create_water': 'Create Water Body',
    'scene.disable_water': 'Disable Water',
    'scene.undo': 'Undo',
    'scene.clear': 'Clear Canvas',
    'scene.download': 'Download Scene',
    'scene.info': 'Information',
    'scene.info_text': 'Click on canvas to place textures or sprites. Use brush size to control texture placement. Water mode creates lakes or rivers automatically.',
    'scene.grass': 'Grass',
    'scene.dirt': 'Dirt',
    'scene.water': 'Water',
    'scene.stone': 'Stone',
    'scene.small_house': 'Small House',
    'scene.large_house': 'Large House',
    'scene.windmill': 'Windmill',
    'scene.well': 'Well',
    'scene.oak_tree': 'Oak Tree',
    'scene.pine_tree': 'Pine Tree',
    'scene.crop': 'Crop',
    'scene.campfire': 'Campfire',
    'scene.barrel': 'Barrel',
    
    // Wallet options
    'wallet.petra': 'Petra Wallet',
    'wallet.martian': 'Martian Wallet',
    'wallet.pontem': 'Pontem Wallet',
    'wallet.nightly': 'Nightly Wallet',
    'wallet.demo': 'Demo Mode',
    
    // Network
    'network.testnet': 'Testnet',
    'network.mainnet': 'Mainnet',
    
    // Footer
    'footer.copyright': 'GUILAND NFT Platform ©2025',
    
    // Landing page
    'landing.title': 'Welcome to GUILAND',
    'landing.subtitle': 'NFT Gaming Platform on Aptos',
    'landing.start_button': 'Get Started',
    'landing.connect_wallet': 'Connect Wallet',
    'landing.start_game': 'Start Game',
    'landing.learn_more': 'Learn More',
    'landing.hero_subtitle': 'NFT Gaming World on Aptos Blockchain',
    'landing.hero_description': 'Create, trade and battle with unique NFTs in the exciting world of GUILAND. Join thousands of players in the first decentralized NFT game on Aptos.',
    'landing.ready_adventure': 'Ready to start your adventure?',
    'landing.join_revolution': 'Join GUILAND today and become part of the NFT gaming revolution',
    'landing.features_title': '🚀 GUILAND Features',
    'landing.features_subtitle': 'Discover the unique capabilities of our platform',
    'landing.mechanics_title': '🎮 Game Mechanics',
    'landing.mechanics_subtitle': 'Immerse yourself in exciting gameplay',
    'landing.stats_players': 'Active Players',
    'landing.stats_nfts': 'Created NFTs',
    'landing.stats_battles': 'Battles Fought',
    'landing.stats_collections': 'Unique Collections',
    'landing.feature_nft_creation': 'NFT Creation',
    'landing.feature_nft_desc': 'Create unique NFTs with customization and royalties',
    'landing.feature_battles': 'Battles',
    'landing.feature_battles_desc': 'Fight other players in epic battles',
    'landing.feature_achievements': 'Achievements',
    'landing.feature_achievements_desc': 'Earn achievements and increase your rank',
    'landing.feature_economy': 'Economy',
    'landing.feature_economy_desc': 'Trade NFTs and earn from the gaming economy',
    'landing.battles_title': 'Battles and Warfare',
    'landing.battles_subtitle': 'Fight other players',
    'landing.battles_description': 'Participate in epic PvP battles, create strategies and prove your superiority on the arena.',
    'landing.start_battle': 'Start Battle',
    'landing.nft_title': 'NFT Creation',
    'landing.nft_subtitle': 'Create unique collections',
    'landing.nft_description': 'Create, trade and collect unique NFT characters with unique abilities.',
    'landing.create_nft': 'Create NFT',
    'landing.achievements_title': 'Achievements and Rating',
    'landing.achievements_subtitle': 'Reach new heights',
    'landing.achievements_description': 'Earn achievements, climb the rankings and become a GUILAND legend.',
    'landing.view_rating': 'View Rating',
    'landing.mechanic_levels': 'Level System',
    'landing.mechanic_levels_desc': 'Level up by gaining experience from in-game actions',
    'landing.mechanic_rating': 'Rating System',
    'landing.mechanic_rating_desc': 'Compete with other players in the global ranking',
    'landing.mechanic_collections': 'NFT Collections',
    'landing.mechanic_collections_desc': 'Collect unique collections and get bonuses',
    'landing.mechanic_pvp': 'PvP Battles',
    'landing.mechanic_pvp_desc': 'Fight in real-time with other players',
    'landing.testimonials_title': '💬 What players say',
    'landing.testimonials_subtitle': 'Reviews from our satisfied players',
    'landing.testimonial_1_name': 'Alex',
    'landing.testimonial_1_role': 'Player',
    'landing.testimonial_1_text': 'Great game! The NFT system works perfectly, and the battles are very exciting.',
    'landing.testimonial_2_name': 'Maria',
    'landing.testimonial_2_role': 'Collector',
    'landing.testimonial_2_text': 'I love collecting NFTs in this game. Each token is unique and has its own story.',
    'landing.testimonial_3_name': 'Dmitry',
    'landing.testimonial_3_role': 'Trader',
    'landing.testimonial_3_text': 'Great game economy. You can earn well from NFT trading.',
    
    // Game page
    'game.title': 'GUILAND Game',
    'game.play_button': 'Play Game',
    'game.welcome': 'Welcome to GUILAND',
    'game.connect_description': 'Connect your Web3 wallet to create and manage NFTs',
    'game.supported_wallets': 'Supported wallets: Petra, Martian, Pontem, Nightly',
    'game.select_wallet': 'Select Wallet',
    'game.create_nft': '🎨 Create NFT',
    'game.balance': '💰 Balance',
    'game.refresh_balance': 'Refresh Balance',
    'game.wallet_info': '📊 Wallet Information',
    'game.wallet_address': 'Wallet Address:',
    'game.wallet_name': 'Wallet:',
    'game.network': 'Network:',
    'game.status': 'Status:',
    'game.connected': 'Connected ✅',
    'game.open_profile': 'Open Profile',
    'game.my_nfts': '🖼️ My NFTs',
    'game.create_character': 'Create Character',
    'game.create_character_desc': 'Create your character to start the game',
    'game.refresh_data': 'Refresh Data',
    'game.check_player': 'Check Player',
    'game.create_player_forced': 'Create Player (Forced)',
    'game.load_player_data': 'Load Player Data',
    'game.test_data': 'Test Data',
    'game.loading_player': 'Loading player data...',
    'game.character': 'Character',
    'game.character_tip': 'Collect resources from territories and level up to increase stats.',
    'game.level': 'Level',
    'game.ready_for_levelup': 'Ready to level up!',
    'game.need_xp': 'Need more XP',
    'game.reputation': 'Reputation',
    'game.last_battle': 'Last Battle',
    'game.never': 'Never',
    'game.territories': 'Territories',
    'game.equipment': 'Equipment',
    'game.guild': 'Guild',
    'game.not_member': 'Not a member',
    'game.collect_resources': 'Collect Resources',
    'game.level_up': 'Level Up (1000 XP)',
    'game.resources': 'Resources',
    'game.resources_tip': 'GUI tokens - main currency, treats - for trading, crystals - rare resource.',
    'game.gui_tokens': 'GUI Tokens',
    'game.treats': 'Treats',
    'game.crystals': 'Crystals',
    'game.loyalty_points': 'Loyalty Points',
    'game.stats': 'Stats',
    'game.stats_tip': 'Stats affect combat effectiveness and economy.',
    'game.attack': 'Attack',
    'game.defense': 'Defense',
    'game.speed': 'Speed',
    'game.leadership': 'Leadership',
    'game.strategy': 'Strategy',
    'game.economy': 'Economy',
    'game.guilds': 'Guilds',
    'game.guilds_tip': 'Create guilds or join existing ones. Guild contributions give loyalty points.',
    'game.create_guild': 'Create Guild',
    'game.guild_name': 'Guild Name',
    'game.create_guild_cost': 'Create (10,000 GUI)',
    'game.join_guild': 'Join Guild',
    'game.guild_id': 'Guild ID',
    'game.join': 'Join',
    'game.guild_contribution': 'Guild Contribution',
    'game.contribute': 'Contribute',
    'game.available_guilds': 'Available Guilds',
    'game.no_guilds_available': 'No guilds available',
    'game.already_member': 'Already a member',
    'game.leader': 'Leader',
    'game.treasury': 'Treasury',
    'game.territories_title': 'Territories',
    'game.territories_tip': 'Attack territories to gain experience and resources. Captured territories provide income every hour.',
    'game.terrain_type': 'Type',
    'game.defense_rating': 'Defense',
    'game.resource_multiplier': 'Resource Multiplier',
    'game.owner': 'Owner',
    'game.attack_territory': 'Attack',
    'game.capture_territory': 'Capture',
    'game.your_territory': 'Your Territory',
    'game.occupied': 'Occupied',
    'game.free': 'Free',
    'game.game_stats': 'Game Statistics',
    'game.total_players': 'Total Players',
    'game.total_guilds': 'Total Guilds',
    'game.game_status': 'Game Status',
    'game.paused': 'Paused',
    'game.active': 'Active',
    'game.update': 'Update',
    'game.terrain_plains': 'Plains',
    'game.terrain_mountains': 'Mountains',
    'game.terrain_forest': 'Forest',
    'game.terrain_mines': 'Mines',
    'game.terrain_port': 'Port',
    'game.terrain_unknown': 'Unknown',
    'game.welcome_guiland': 'Welcome to GUILAND!',
    'game.create_character_tip': 'Create your character to start the game',
    'game.force_check_player': 'Force Check Player',
    'game.force_create_player': 'Force Create Player',
    'game.force_load_player': 'Force Load Player Data',
    'game.player_panel': 'Player Panel',
    'game.game_systems': 'Game Systems',
    
    // Guild Leader Interface
    'guild.leader_panel': 'Guild Leader Panel',
    'guild.leader_welcome': 'Welcome, Guild Leader!',
    'guild.manage_guild': 'Manage Guild',
    'guild.guild_info': 'Guild Information',
    'guild.guild_name': 'Guild Name',
    'guild.guild_level': 'Guild Level',
    'guild.member_count': 'Members',
    'guild.treasury': 'Treasury',
    'guild.territories_owned': 'Territories Owned',
    'guild.tax_rate': 'Tax Rate',
    'guild.creation_date': 'Creation Date',
    'guild.members_management': 'Members Management',
    'guild.member_list': 'Member List',
    'guild.member_name': 'Member',
    'guild.member_level': 'Level',
    'guild.member_contribution': 'Contribution',
    'guild.member_join_date': 'Join Date',
    'guild.kick_member': 'Kick Member',
    'guild.promote_member': 'Promote to Officer',
    'guild.demote_member': 'Demote from Officer',
    'guild.transfer_leadership': 'Transfer Leadership',
    'guild.guild_settings': 'Guild Settings',
    'guild.change_name': 'Change Guild Name',
    'guild.new_name': 'New Name',
    'guild.update_name': 'Update Name',
    'guild.change_tax_rate': 'Change Tax Rate',
    'guild.new_tax_rate': 'New Tax Rate (%)',
    'guild.update_tax_rate': 'Update Tax Rate',
    'guild.guild_announcements': 'Guild Announcements',
    'guild.announcement': 'Announcement',
    'guild.post_announcement': 'Post Announcement',
    'guild.guild_events': 'Guild Events',
    'guild.create_event': 'Create Event',
    'guild.event_name': 'Event Name',
    'guild.event_description': 'Event Description',
    'guild.event_date': 'Event Date',
    'guild.event_reward': 'Event Reward',
    'guild.create_event_button': 'Create Event',
    'guild.guild_war': 'Guild War',
    'guild.declare_war': 'Declare War',
    'guild.target_guild': 'Target Guild',
    'guild.war_duration': 'War Duration (hours)',
    'guild.declare_war_button': 'Declare War',
    'guild.guild_alliance': 'Guild Alliance',
    'guild.propose_alliance': 'Propose Alliance',
    'guild.alliance_guild': 'Alliance Guild',
    'guild.alliance_terms': 'Alliance Terms',
    'guild.propose_alliance_button': 'Propose Alliance',
    'guild.guild_statistics': 'Guild Statistics',
    'guild.total_contributions': 'Total Contributions',
    'guild.average_level': 'Average Level',
    'guild.battles_won': 'Battles Won',
    'guild.territories_captured': 'Territories Captured',
    'guild.guild_rank': 'Guild Rank',
    'guild.guild_permissions': 'Guild Permissions',
    'guild.can_invite': 'Can Invite Members',
    'guild.can_kick': 'Can Kick Members',
    'guild.can_promote': 'Can Promote Members',
    'guild.can_manage_events': 'Can Manage Events',
    'guild.can_declare_war': 'Can Declare War',
    'guild.guild_logs': 'Guild Activity Log',
    'guild.recent_activity': 'Recent Activity',
    'guild.activity_member_joined': 'Member joined',
    'guild.activity_member_left': 'Member left',
    'guild.activity_contribution': 'Contribution made',
    'guild.activity_territory_captured': 'Territory captured',
    'guild.activity_battle_won': 'Battle won',
    'guild.guild_achievements': 'Guild Achievements',
    'guild.achievement_unlocked': 'Achievement Unlocked',
    'guild.achievement_members_10': '10 Members',
    'guild.achievement_members_50': '50 Members',
    'guild.achievement_members_100': '100 Members',
    'guild.achievement_territories_5': '5 Territories',
    'guild.achievement_territories_10': '10 Territories',
    'guild.achievement_level_10': 'Level 10 Guild',
    'guild.achievement_level_25': 'Level 25 Guild',
    'guild.achievement_level_50': 'Level 50 Guild',
    
    // Guild Members Management
    'guild.guild_members': 'Guild Members',
    'guild.promote': 'Promote',
    'guild.kick': 'Kick',
    'guild.officer': 'Officer',
    'guild.contribution': 'Contribution',
    'guild.joined': 'Joined',
    'guild.advanced_management_coming_soon': 'Advanced Management',
    'guild.advanced_management_description': 'Advanced member management features will be available in the next update',
    'guild.invite_member': 'Invite Member',
    'guild.current_name': 'Current Name',
    'guild.current_tax_rate': 'Current Tax Rate',
    'guild.announcements_description': 'Post announcements for all guild members',
    'guild.events_description': 'Create events for guild members',
    'guild.war_description': 'Declare war on other guilds',
    'guild.alliance_description': 'Propose alliances with other guilds',
    'guild.current_treasury': 'Current Treasury',
    'guild.treasury_management_coming_soon': 'Treasury Management',
    'guild.treasury_description': 'Advanced treasury management will be available in the next update',
    'guild.distribute_resources': 'Distribute Resources',
    'guild.view_history': 'View History',
    'guild.events_coming_soon': 'Guild Events',
    'guild.no_activity': 'No activity yet',
    'guild.detailed_logs_coming_soon': 'Detailed Logs',
    'guild.detailed_logs_description': 'Detailed activity logging system will be available in the next update',
    'guild.export_logs': 'Export Logs',
    'guild.statistics_note': 'Statistics will be updated as the game develops',
    'guild.guild_created': 'Guild created',
    'guild.you': 'You',
    'guild.last_active': 'Last Active',
    'guild.online': 'Online',
    'guild.ago': 'ago',
    'guild.actions': 'Actions',
    'guild.send_message': 'Send Message',
    'guild.set_permissions': 'Set Permissions',
    'guild.kick_member_confirm': 'Kick Member',
    'guild.kick_member_warning': 'Are you sure you want to kick this member?',
    'guild.message_sent': 'Message sent successfully',
    'guild.permissions_updated': 'Permissions updated successfully',
    'guild.send_message_to': 'Send Message to',
    'guild.message': 'Message',
    'guild.message_placeholder': 'Enter your message...',
    'guild.set_permissions_for': 'Set Permissions for',
    'guild.permissions': 'Permissions',
    'guild.select_permissions': 'Select permissions',
    'guild.update_permissions': 'Update Permissions',
    'guild.can_manage_treasury': 'Can Manage Treasury',
    'guild.can_view_logs': 'Can View Logs',
    
    // Guild Treasury Management
    'guild.treasury_management': 'Treasury Management',
    'guild.distribute_resources': 'Distribute Resources',
    'guild.transaction_history': 'Transaction History',
    'guild.resource_distribution': 'Resource Distribution',
    'guild.recent_transactions': 'Recent Transactions',
    'guild.transaction_type': 'Transaction Type',
    'guild.deposit': 'Deposit',
    'guild.withdrawal': 'Withdrawal',
    'guild.distribution': 'Distribution',
    'guild.tax': 'Tax',
    'guild.from': 'From',
    'guild.to': 'To',
    'guild.description': 'Description',
    'guild.timestamp': 'Timestamp',
    'guild.status': 'Status',
    'guild.pending': 'Pending',
    'guild.completed': 'Completed',
    'guild.failed': 'Failed',
    'guild.resources_distributed': 'Resources distributed successfully',
    'guild.resources_withdrawn': 'Resources withdrawn successfully',
    'guild.tax_rate_updated': 'Tax rate updated successfully',
    'guild.select_member': 'Select Member',
    'guild.currency': 'Currency',
    'guild.select_currency': 'Select currency',
    'guild.amount': 'Amount',
    'guild.distribute': 'Distribute',
    'guild.withdraw_resources': 'Withdraw Resources',
    'guild.reason': 'Reason',
    'guild.withdrawal_reason': 'Enter withdrawal reason...',
    'guild.withdraw': 'Withdraw',
    'guild.set_tax_rate': 'Set Tax Rate',
    'guild.tax_rate_percentage': 'Tax Rate (%)',
    
    // Guild Events Management
    'guild.events_management': 'Events Management',
    'guild.events_calendar': 'Events Calendar',
    'guild.upcoming_events': 'Upcoming Events',
    'guild.events_statistics': 'Events Statistics',
    'guild.total_events': 'Total Events',
    'guild.completed_events': 'Completed Events',
    'guild.avg_participants': 'Avg Participants',
    'guild.event_created': 'Event created successfully',
    'guild.event_updated': 'Event updated successfully',
    'guild.event_deleted': 'Event deleted successfully',
    'guild.edit_event': 'Edit Event',
    'guild.event_type': 'Event Type',
    'guild.select_event_type': 'Select event type',
    'guild.event_type_battle': 'Battle',
    'guild.event_type_training': 'Training',
    'guild.event_type_social': 'Social',
    'guild.event_type_competition': 'Competition',
    'guild.event_type_meeting': 'Meeting',
    'guild.event_status_upcoming': 'Upcoming',
    'guild.event_status_ongoing': 'Ongoing',
    'guild.event_status_completed': 'Completed',
    'guild.event_status_cancelled': 'Cancelled',
    'guild.participants': 'Participants',
    'guild.event_time': 'Event Time',
    'guild.event_duration': 'Event Duration',
    'guild.hours': 'hours',
    'guild.max_participants': 'Max Participants',
    'guild.event_location': 'Event Location',
    'guild.event_location_placeholder': 'Enter event location...',
    'guild.event_requirements': 'Event Requirements',
    'guild.event_requirements_placeholder': 'Enter requirements...',
    'guild.update_event': 'Update Event',
    
    // Profile page
    'profile.title': 'Profile',
    'profile.address': 'Address',
    'profile.balance': 'Balance',
    'profile.player': 'Player #',
    'profile.wallet_address': 'Wallet Address:',
    'profile.network': 'Network:',
    'profile.level': 'Level:',
    'profile.address_copied': 'Address copied to clipboard',
    'profile.load_error': 'Error loading player data',
    'profile.total_nfts': 'Total NFTs',
    'profile.collections': 'Collections',
    'profile.victories': 'Victories',
    'profile.achievements': 'Achievements',
    'profile.my_nfts': '🖼️ My NFTs',
    'profile.battles': '⚔️ Battles',
    'profile.battle_stats': 'Battle Statistics',
    'profile.wins': 'Wins:',
    'profile.losses': 'Losses:',
    'profile.win_rate': 'Win Rate:',
    'profile.recent_battles': 'Recent Battles',
    'profile.opponent': 'Player #',
    'profile.victory': 'Victory',
    'profile.defeat': 'Defeat',
    'profile.achievements_tab': '🏆 Achievements',
    'profile.first_nft': 'First NFT',
    'profile.first_nft_desc': 'Create your first NFT',
    'profile.collector': 'Collector',
    'profile.collector_desc': 'Collect 5 unique NFTs',
    'profile.warrior': 'Warrior',
    'profile.warrior_desc': 'Win 10 battles',
    'profile.legend': 'Legend',
    'profile.legend_desc': 'Reach level 10',
    'profile.master': 'Master',
    'profile.master_desc': 'Create 50 NFTs',
    'profile.ranks': {
      'Новичок': 'Novice',
      'Опытный': 'Experienced',
      'Ветеран': 'Veteran',
      'Мастер': 'Master',
      'Легенда': 'Legend'
    },
    
    // NFT components
    'nft.mint': 'Mint NFT',
    'nft.gallery': 'NFT Gallery',
    'nft.no_nfts': 'No NFTs found',
    'nft.connect_wallet': 'Connect wallet to create NFT',
    'nft.wallet': 'Wallet:',
    'nft.network': 'Network:',
    'nft.name': 'NFT Name',
    'nft.name_placeholder': 'My unique NFT',
    'nft.name_required': 'Enter NFT name',
    'nft.description': 'Description',
    'nft.description_placeholder': 'Description of your NFT...',
    'nft.description_required': 'Enter NFT description',
    'nft.uri': 'Metadata URI',
    'nft.uri_placeholder': 'https://example.com/metadata.json',
    'nft.uri_required': 'Enter metadata URI',
    'nft.upload_file': 'Or upload file',
    'nft.upload': 'Upload',
    'nft.create_via_wallet': 'Create NFT via wallet',
    'nft.royalty_note': '* Royalty: 5% from sales',
    'nft.connect_first': 'Connect wallet first!',
    'nft.success_created': 'NFT successfully created! Hash:',
    'nft.error_creating': 'Error creating NFT:',
    'nft.unknown_error': 'Unknown error',
    'nft.connect_to_view': 'Connect wallet to view NFTs',
    'nft.loading': 'Loading NFTs...',
    'nft.your_nfts': 'Your NFTs',
    'nft.refresh': 'Refresh',
    'nft.no_nfts_yet': 'You have no NFTs yet',
    'nft.view': 'View',
    'nft.transfer': 'Transfer',
    'nft.burn': 'Burn',
    'nft.token_id': 'Token ID:',
    'nft.collection': 'GUILAND NFT Collection',
    'nft.quantity': 'Quantity:',
    'nft.wallet_no_transactions': 'Wallet does not support transactions',
    'nft.transfer_success': 'NFT successfully transferred!',
    'nft.transfer_error': 'Error transferring NFT:',
    'nft.burn_success': 'NFT successfully burned!',
    'nft.burn_error': 'Error burning NFT:',
    'nft.load_error': 'Error loading NFTs',
    'nft.token_data_error': 'Error getting token data:',
    'nft.castle_description': 'Majestic castle in the world of GUILAND',
    'nft.dragon_description': 'Guardian of the GUILAND kingdom',
    'nft.sword_description': 'Legendary sword with magical properties',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.required': 'is required',
    'common.confirm': 'Confirm',
    'common.test': 'Test',
    'common.normal_mode': 'Normal Mode',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.close': 'Close',
    'common.open': 'Open',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.refresh': 'Refresh',
    'common.download': 'Download',
    'common.upload': 'Upload',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.settings': 'Settings',
    'common.help': 'Help',
    'common.about': 'About',
    'common.contact': 'Contact',
    'common.privacy': 'Privacy',
    'common.terms': 'Terms',
    'common.language': 'Language',
    'common.install': 'Install',
    'common.wallet': 'wallet',
    'common.and': 'and',
    'common.page': 'page',
    'common.coming_soon': 'Coming Soon',
  },
  ru: {
    // Header
    'header.home': 'Главная',
    'header.game': 'Игра',
    'header.scene_generator': 'Генератор сцен',
    'header.connect_wallet': 'Подключить кошелек',
    'header.disconnect': 'Отключить',
    'header.profile': 'Профиль',
    'header.demo_mode': 'Демо режим',
    'header.test_wallets': 'Тест кошельков',
    
    // Scene Generator
    'scene.generator_title': 'Генератор сцен',
    'scene.generator_description': 'Создавайте пиксель-арт сцены с текстурами и спрайтами',
    'scene.canvas': 'Холст',
    'scene.controls': 'Управление',
    'scene.draw_mode': 'Режим рисования',
    'scene.texture_mode': 'Режим текстур',
    'scene.sprite_mode': 'Режим спрайтов',
    'scene.select_texture': 'Выбрать текстуру',
    'scene.select_sprite': 'Выбрать спрайт',
    'scene.brush_size': 'Размер кисти',
    'scene.water_mode': 'Водный режим',
    'scene.create_water': 'Создать водоем',
    'scene.disable_water': 'Отключить воду',
    'scene.undo': 'Отменить',
    'scene.clear': 'Очистить холст',
    'scene.download': 'Скачать сцену',
    'scene.info': 'Информация',
    'scene.info_text': 'Кликните на холст для размещения текстур или спрайтов. Используйте размер кисти для контроля размещения текстур. Водный режим автоматически создает озера или реки.',
    'scene.grass': 'Трава',
    'scene.dirt': 'Земля',
    'scene.water': 'Вода',
    'scene.stone': 'Камень',
    'scene.small_house': 'Малый дом',
    'scene.large_house': 'Большой дом',
    'scene.windmill': 'Мельница',
    'scene.well': 'Колодец',
    'scene.oak_tree': 'Дуб',
    'scene.pine_tree': 'Сосна',
    'scene.crop': 'Урожай',
    'scene.campfire': 'Костер',
    'scene.barrel': 'Бочка',
    
    // Wallet options
    'wallet.petra': 'Petra Wallet',
    'wallet.martian': 'Martian Wallet',
    'wallet.pontem': 'Pontem Wallet',
    'wallet.nightly': 'Nightly Wallet',
    'wallet.demo': 'Демо режим',
    
    // Network
    'network.testnet': 'Тестнет',
    'network.mainnet': 'Мейннет',
    
    // Footer
    'footer.copyright': 'GUILAND NFT Платформа ©2025',
    
    // Landing page
    'landing.title': 'Добро пожаловать в GUILAND',
    'landing.subtitle': 'NFT Игровая платформа на Aptos',
    'landing.start_button': 'Начать',
    'landing.connect_wallet': 'Подключить кошелек',
    'landing.start_game': 'Начать игру',
    'landing.learn_more': 'Узнать больше',
    'landing.hero_subtitle': 'Мир NFT игр на блокчейне Aptos',
    'landing.hero_description': 'Создавайте, торгуйте и сражайтесь с уникальными NFT в захватывающем мире GUILAND. Присоединяйтесь к тысячам игроков в первой децентрализованной NFT игре на Aptos.',
    'landing.ready_adventure': '🚀 Готовы начать приключение?',
    'landing.join_revolution': 'Присоединяйтесь к GUILAND сегодня и станьте частью революции в мире NFT игр',
    'landing.features_title': '🚀 Особенности GUILAND',
    'landing.features_subtitle': 'Откройте для себя уникальные возможности нашей платформы',
    'landing.mechanics_title': '🎮 Игровые механики',
    'landing.mechanics_subtitle': 'Погрузитесь в захватывающий игровой процесс',
    'landing.stats_players': 'Активных игроков',
    'landing.stats_nfts': 'Созданных NFT',
    'landing.stats_battles': 'Проведенных битв',
    'landing.stats_collections': 'Уникальных коллекций',
    'landing.feature_nft_creation': 'Создание NFT',
    'landing.feature_nft_desc': 'Создавайте уникальные NFT с кастомизацией и роялти',
    'landing.feature_battles': 'Битвы',
    'landing.feature_battles_desc': 'Сражайтесь с другими игроками в эпических битвах',
    'landing.feature_achievements': 'Достижения',
    'landing.feature_achievements_desc': 'Зарабатывайте достижения и повышайте свой ранг',
    'landing.feature_economy': 'Экономика',
    'landing.feature_economy_desc': 'Торгуйте NFT и зарабатывайте на игровой экономике',
    'landing.battles_title': 'Битвы и Сражения',
    'landing.battles_subtitle': 'Сражайтесь с другими игроками',
    'landing.battles_description': 'Участвуйте в эпических PvP битвах, создавайте стратегии и докажите свое превосходство на арене.',
    'landing.start_battle': 'Начать битву',
    'landing.nft_title': 'Создание NFT',
    'landing.nft_subtitle': 'Создавайте уникальные коллекции',
    'landing.nft_description': 'Создавайте, торгуйте и коллекционируйте уникальные NFT персонажей с уникальными способностями.',
    'landing.create_nft': 'Создать NFT',
    'landing.achievements_title': 'Достижения и Рейтинг',
    'landing.achievements_subtitle': 'Достигайте новых высот',
    'landing.achievements_description': 'Зарабатывайте достижения, поднимайтесь в рейтинге и станьте легендой GUILAND.',
    'landing.view_rating': 'Посмотреть рейтинг',
    'landing.mechanic_levels': 'Система уровней',
    'landing.mechanic_levels_desc': 'Повышайте уровень, получая опыт за действия в игре',
    'landing.mechanic_rating': 'Рейтинговая система',
    'landing.mechanic_rating_desc': 'Соревнуйтесь с другими игроками в глобальном рейтинге',
    'landing.mechanic_collections': 'Коллекции NFT',
    'landing.mechanic_collections_desc': 'Собирайте уникальные коллекции и получайте бонусы',
    'landing.mechanic_pvp': 'PvP битвы',
    'landing.mechanic_pvp_desc': 'Сражайтесь в реальном времени с другими игроками',
    'landing.testimonials_title': '💬 Что говорят игроки',
    'landing.testimonials_subtitle': 'Отзывы от наших довольных игроков',
    'landing.testimonial_1_name': 'Алексей',
    'landing.testimonial_1_role': 'Игрок',
    'landing.testimonial_1_text': 'Отличная игра! NFT система работает идеально, а битвы очень увлекательные.',
    'landing.testimonial_2_name': 'Мария',
    'landing.testimonial_2_role': 'Коллекционер',
    'landing.testimonial_2_text': 'Люблю собирать NFT в этой игре. Каждый токен уникален и имеет свою историю.',
    'landing.testimonial_3_name': 'Дмитрий',
    'landing.testimonial_3_role': 'Трейдер',
    'landing.testimonial_3_text': 'Отличная экономика игры. Можно хорошо заработать на торговле NFT.',
    
    // Game page
    'game.title': 'GUILAND Игра',
    'game.play_button': 'Играть',
    'game.welcome': 'Добро пожаловать в GUILAND',
    'game.connect_description': 'Подключите Web3 кошелек для создания и управления NFT',
    'game.supported_wallets': 'Поддерживаемые кошельки: Petra, Martian, Pontem, Nightly',
    'game.select_wallet': 'Выбрать кошелек',
    'game.create_nft': '🎨 Создать NFT',
    'game.balance': '💰 Баланс',
    'game.refresh_balance': 'Обновить баланс',
    'game.wallet_info': '📊 Информация о кошельке',
    'game.wallet_address': 'Адрес кошелька:',
    'game.wallet_name': 'Кошелек:',
    'game.network': 'Сеть:',
    'game.status': 'Статус:',
    'game.connected': 'Подключен ✅',
    'game.open_profile': 'Открыть профиль',
    'game.my_nfts': '🖼️ Мои NFT',
    'game.create_character': 'Создать персонажа',
    'game.create_character_desc': 'Создайте своего персонажа, чтобы начать игру',
    'game.refresh_data': 'Обновить данные',
    'game.check_player': 'Проверить игрока',
    'game.create_player_forced': 'Создать игрока (принудительно)',
    'game.load_player_data': 'Загрузить данные игрока',
    'game.test_data': 'Тестовые данные',
    'game.loading_player': 'Загрузка данных игрока...',
    'game.character': 'Персонаж',
    'game.character_tip': 'Собирайте ресурсы с территорий и повышайте уровень для увеличения характеристик.',
    'game.level': 'Уровень',
    'game.ready_for_levelup': 'Готов к повышению уровня!',
    'game.need_xp': 'Нужно еще XP',
    'game.reputation': 'Репутация',
    'game.last_battle': 'Последняя битва',
    'game.never': 'Не было',
    'game.territories': 'Территории',
    'game.equipment': 'Экипировка',
    'game.guild': 'Гильдия',
    'game.not_member': 'Не состоит',
    'game.collect_resources': 'Собрать ресурсы',
    'game.level_up': 'Повысить уровень (1000 XP)',
    'game.resources': 'Ресурсы',
    'game.resources_tip': 'GUI токены - основная валюта, угощения - для торговли, кристаллы - редкий ресурс.',
    'game.gui_tokens': 'GUI токены',
    'game.treats': 'Угощения',
    'game.crystals': 'Кристаллы',
    'game.loyalty_points': 'Очки лояльности',
    'game.stats': 'Характеристики',
    'game.stats_tip': 'Характеристики влияют на боевую эффективность и экономику.',
    'game.attack': 'Атака',
    'game.defense': 'Защита',
    'game.speed': 'Скорость',
    'game.leadership': 'Лидерство',
    'game.strategy': 'Стратегия',
    'game.economy': 'Экономика',
    'game.guilds': 'Гильдии',
    'game.guilds_tip': 'Создавайте гильдии или присоединяйтесь к существующим. Взносы в гильдию дают очки лояльности.',
    'game.create_guild': 'Создать гильдию',
    'game.guild_name': 'Название гильдии',
    'game.create_guild_cost': 'Создать (10,000 GUI)',
    'game.join_guild': 'Присоединиться к гильдии',
    'game.guild_id': 'ID гильдии',
    'game.join': 'Присоединиться',
    'game.guild_contribution': 'Взнос в гильдию',
    'game.contribute': 'Внести взнос',
    'game.available_guilds': 'Доступные гильдии',
    'game.no_guilds_available': 'Нет доступных гильдий',
    'game.already_member': 'Уже участник',
    'game.leader': 'Лидер',
    'game.treasury': 'Казна',
    'game.territories_title': 'Территории',
    'game.territories_tip': 'Атакуйте территории для получения опыта и ресурсов. Захваченные территории приносят доход каждый час.',
    'game.terrain_type': 'Тип',
    'game.defense_rating': 'Защита',
    'game.resource_multiplier': 'Множитель ресурсов',
    'game.owner': 'Владелец',
    'game.attack_territory': 'Атаковать',
    'game.capture_territory': 'Захватить',
    'game.your_territory': 'Ваша территория',
    'game.occupied': 'Занята',
    'game.free': 'Свободна',
    'game.game_stats': 'Статистика игры',
    'game.total_players': 'Всего игроков',
    'game.total_guilds': 'Всего гильдий',
    'game.game_status': 'Статус игры',
    'game.paused': 'Приостановлена',
    'game.active': 'Активна',
    'game.update': 'Обновить',
    'game.terrain_plains': 'Равнина',
    'game.terrain_mountains': 'Горы',
    'game.terrain_forest': 'Лес',
    'game.terrain_mines': 'Шахты',
    'game.terrain_port': 'Порт',
    'game.terrain_unknown': 'Неизвестно',
    'game.welcome_guiland': 'Добро пожаловать в GUILAND!',
    'game.create_character_tip': 'Создайте своего персонажа, чтобы начать игру',
    'game.force_check_player': 'Принудительная проверка игрока',
    'game.force_create_player': 'Принудительное создание игрока',
    'game.force_load_player': 'Принудительная загрузка данных игрока',
    'game.player_panel': 'Панель игрока',
    'game.game_systems': 'Игровые системы',
    
    // Guild Leader Interface
    'guild.leader_panel': 'Панель лидера гильдии',
    'guild.leader_welcome': 'Добро пожаловать, лидер гильдии!',
    'guild.manage_guild': 'Управление гильдией',
    'guild.guild_info': 'Информация о гильдии',
    'guild.guild_name': 'Название гильдии',
    'guild.guild_level': 'Уровень гильдии',
    'guild.member_count': 'Участники',
    'guild.treasury': 'Казна',
    'guild.territories_owned': 'Захваченные территории',
    'guild.tax_rate': 'Налоговая ставка',
    'guild.creation_date': 'Дата создания',
    'guild.members_management': 'Управление участниками',
    'guild.member_list': 'Список участников',
    'guild.member_name': 'Участник',
    'guild.member_level': 'Уровень',
    'guild.member_contribution': 'Вклад',
    'guild.member_join_date': 'Дата вступления',
    'guild.kick_member': 'Исключить участника',
    'guild.promote_member': 'Повысить до офицера',
    'guild.demote_member': 'Понизить с офицера',
    'guild.transfer_leadership': 'Передать лидерство',
    'guild.guild_settings': 'Настройки гильдии',
    'guild.change_name': 'Изменить название гильдии',
    'guild.new_name': 'Новое название',
    'guild.update_name': 'Обновить название',
    'guild.change_tax_rate': 'Изменить налоговую ставку',
    'guild.new_tax_rate': 'Новая налоговая ставка (%)',
    'guild.update_tax_rate': 'Обновить налоговую ставку',
    'guild.guild_announcements': 'Объявления гильдии',
    'guild.announcement': 'Объявление',
    'guild.post_announcement': 'Опубликовать объявление',
    'guild.guild_events': 'События гильдии',
    'guild.create_event': 'Создать событие',
    'guild.event_name': 'Название события',
    'guild.event_description': 'Описание события',
    'guild.event_date': 'Дата события',
    'guild.event_reward': 'Награда за событие',
    'guild.create_event_button': 'Создать событие',
    'guild.guild_war': 'Война гильдий',
    'guild.declare_war': 'Объявить войну',
    'guild.target_guild': 'Целевая гильдия',
    'guild.war_duration': 'Продолжительность войны (часы)',
    'guild.declare_war_button': 'Объявить войну',
    'guild.guild_alliance': 'Альянс гильдий',
    'guild.propose_alliance': 'Предложить альянс',
    'guild.alliance_guild': 'Гильдия для альянса',
    'guild.alliance_terms': 'Условия альянса',
    'guild.propose_alliance_button': 'Предложить альянс',
    'guild.guild_statistics': 'Статистика гильдии',
    'guild.total_contributions': 'Общий вклад',
    'guild.average_level': 'Средний уровень',
    'guild.battles_won': 'Выигранные битвы',
    'guild.territories_captured': 'Захваченные территории',
    'guild.guild_rank': 'Ранг гильдии',
    'guild.guild_permissions': 'Разрешения гильдии',
    'guild.can_invite': 'Может приглашать участников',
    'guild.can_kick': 'Может исключать участников',
    'guild.can_promote': 'Может повышать участников',
    'guild.can_manage_events': 'Может управлять событиями',
    'guild.can_declare_war': 'Может объявлять войны',
    'guild.guild_logs': 'Журнал активности гильдии',
    'guild.recent_activity': 'Последняя активность',
    'guild.activity_member_joined': 'Участник присоединился',
    'guild.activity_member_left': 'Участник покинул',
    'guild.activity_contribution': 'Сделан вклад',
    'guild.activity_territory_captured': 'Захвачена территория',
    'guild.activity_battle_won': 'Выиграна битва',
    'guild.guild_achievements': 'Достижения гильдии',
    'guild.achievement_unlocked': 'Достижение разблокировано',
    'guild.achievement_members_10': '10 участников',
    'guild.achievement_members_50': '50 участников',
    'guild.achievement_members_100': '100 участников',
    'guild.achievement_territories_5': '5 территорий',
    'guild.achievement_territories_10': '10 территорий',
    'guild.achievement_level_10': 'Гильдия 10 уровня',
    'guild.achievement_level_25': 'Гильдия 25 уровня',
    'guild.achievement_level_50': 'Гильдия 50 уровня',
    
    // Guild Members Management
    'guild.guild_members': 'Участники гильдии',
    'guild.promote': 'Повысить',
    'guild.kick': 'Исключить',
    'guild.officer': 'Офицер',
    'guild.contribution': 'Вклад',
    'guild.joined': 'Присоединился',
    'guild.advanced_management_coming_soon': 'Расширенное управление',
    'guild.advanced_management_description': 'Расширенные функции управления участниками будут доступны в ближайшем обновлении',
    'guild.invite_member': 'Пригласить участника',
    'guild.current_name': 'Текущее название',
    'guild.current_tax_rate': 'Текущая налоговая ставка',
    'guild.announcements_description': 'Публикуйте объявления для всех участников гильдии',
    'guild.events_description': 'Создавайте события для участников гильдии',
    'guild.war_description': 'Объявляйте войну другим гильдиям',
    'guild.alliance_description': 'Предлагайте альянсы другим гильдиям',
    'guild.current_treasury': 'Текущая казна',
    'guild.treasury_management_coming_soon': 'Управление казной',
    'guild.treasury_description': 'Расширенное управление казной гильдии будет доступно в ближайшем обновлении',
    'guild.distribute_resources': 'Распределить ресурсы',
    'guild.view_history': 'Просмотреть историю',
    'guild.events_coming_soon': 'События гильдии',
    'guild.no_activity': 'Пока нет активности',
    'guild.detailed_logs_coming_soon': 'Подробные логи',
    'guild.detailed_logs_description': 'Подробная система логов активности будет доступна в ближайшем обновлении',
    'guild.export_logs': 'Экспорт логов',
    'guild.statistics_note': 'Статистика будет обновляться по мере развития игры',
    'guild.guild_created': 'Гильдия создана',
    'guild.you': 'Вы',
    'guild.last_active': 'Последняя активность',
    'guild.online': 'В сети',
    'guild.ago': 'назад',
    'guild.actions': 'Действия',
    'guild.send_message': 'Отправить сообщение',
    'guild.kick_member_confirm': 'Исключить участника',
    'guild.kick_member_warning': 'Вы уверены, что хотите исключить этого участника?',
    'guild.message_sent': 'Сообщение отправлено успешно',
    'guild.permissions_updated': 'Разрешения обновлены успешно',
    'guild.send_message_to': 'Отправить сообщение',
    'guild.message': 'Сообщение',
    'guild.message_placeholder': 'Введите ваше сообщение...',
    'guild.set_permissions_for': 'Установить разрешения для',
    'guild.permissions': 'Разрешения',
    'guild.select_permissions': 'Выберите разрешения',
    'guild.update_permissions': 'Обновить разрешения',
    'guild.can_manage_treasury': 'Может управлять казной',
    'guild.can_view_logs': 'Может просматривать логи',
    
    // Guild Treasury Management
    'guild.treasury_management': 'Управление казной',
    'guild.distribute_resources': 'Распределить ресурсы',
    'guild.transaction_history': 'История транзакций',
    'guild.resource_distribution': 'Распределение ресурсов',
    'guild.recent_transactions': 'Последние транзакции',
    'guild.transaction_type': 'Тип транзакции',
    'guild.deposit': 'Пополнение',
    'guild.withdrawal': 'Вывод',
    'guild.distribution': 'Распределение',
    'guild.tax': 'Налог',
    'guild.from': 'От',
    'guild.to': 'К',
    'guild.description': 'Описание',
    'guild.timestamp': 'Время',
    'guild.status': 'Статус',
    'guild.pending': 'В ожидании',
    'guild.completed': 'Завершено',
    'guild.failed': 'Ошибка',
    'guild.resources_distributed': 'Ресурсы распределены успешно',
    'guild.resources_withdrawn': 'Ресурсы выведены успешно',
    'guild.tax_rate_updated': 'Налоговая ставка обновлена успешно',
    'guild.select_member': 'Выбрать участника',
    'guild.currency': 'Валюта',
    'guild.select_currency': 'Выбрать валюту',
    'guild.amount': 'Количество',
    'guild.distribute': 'Распределить',
    'guild.withdraw_resources': 'Вывести ресурсы',
    'guild.reason': 'Причина',
    'guild.withdrawal_reason': 'Введите причину вывода...',
    'guild.withdraw': 'Вывести',
    'guild.set_tax_rate': 'Установить налоговую ставку',
    'guild.tax_rate_percentage': 'Налоговая ставка (%)',
    
    // Guild Events Management
    'guild.events_management': 'Управление событиями',
    'guild.events_calendar': 'Календарь событий',
    'guild.upcoming_events': 'Предстоящие события',
    'guild.events_statistics': 'Статистика событий',
    'guild.total_events': 'Всего событий',
    'guild.completed_events': 'Завершенные события',
    'guild.avg_participants': 'Среднее участников',
    'guild.event_created': 'Событие создано успешно',
    'guild.event_updated': 'Событие обновлено успешно',
    'guild.event_deleted': 'Событие удалено успешно',
    'guild.edit_event': 'Редактировать событие',
    'guild.event_type': 'Тип события',
    'guild.select_event_type': 'Выбрать тип события',
    'guild.event_type_battle': 'Битва',
    'guild.event_type_training': 'Тренировка',
    'guild.event_type_social': 'Социальное',
    'guild.event_type_competition': 'Соревнование',
    'guild.event_type_meeting': 'Встреча',
    'guild.event_status_upcoming': 'Предстоящее',
    'guild.event_status_ongoing': 'Текущее',
    'guild.event_status_completed': 'Завершенное',
    'guild.event_status_cancelled': 'Отмененное',
    'guild.participants': 'Участники',
    'guild.event_time': 'Время события',
    'guild.event_duration': 'Продолжительность события',
    'guild.hours': 'часов',
    'guild.max_participants': 'Максимум участников',
    'guild.event_location': 'Место события',
    'guild.event_location_placeholder': 'Введите место события...',
    'guild.event_requirements': 'Требования к событию',
    'guild.event_requirements_placeholder': 'Введите требования...',
    'guild.update_event': 'Обновить событие',
    
    // Profile page
    'profile.title': 'Профиль',
    'profile.address': 'Адрес',
    'profile.balance': 'Баланс',
    'profile.player': 'Игрок #',
    'profile.wallet_address': 'Адрес кошелька:',
    'profile.network': 'Сеть:',
    'profile.level': 'Уровень:',
    'profile.address_copied': 'Адрес скопирован в буфер обмена',
    'profile.load_error': 'Ошибка загрузки данных игрока',
    'profile.total_nfts': 'Всего NFT',
    'profile.collections': 'Коллекции',
    'profile.victories': 'Победы',
    'profile.achievements': 'Достижения',
    'profile.my_nfts': '🖼️ Мои NFT',
    'profile.battles': '⚔️ Битвы',
    'profile.battle_stats': 'Статистика битв',
    'profile.wins': 'Победы:',
    'profile.losses': 'Поражения:',
    'profile.win_rate': 'Процент побед:',
    'profile.recent_battles': 'Последние битвы',
    'profile.opponent': 'Игрок #',
    'profile.victory': 'Победа',
    'profile.defeat': 'Поражение',
    'profile.achievements_tab': '🏆 Достижения',
    'profile.first_nft': 'Первый NFT',
    'profile.first_nft_desc': 'Создайте свой первый NFT',
    'profile.collector': 'Коллекционер',
    'profile.collector_desc': 'Соберите 5 уникальных NFT',
    'profile.warrior': 'Воин',
    'profile.warrior_desc': 'Выиграйте 10 битв',
    'profile.legend': 'Легенда',
    'profile.legend_desc': 'Достигните 10 уровня',
    'profile.master': 'Мастер',
    'profile.master_desc': 'Создайте 50 NFT',
    'profile.ranks': {
      'Новичок': 'Новичок',
      'Опытный': 'Опытный',
      'Ветеран': 'Ветеран',
      'Мастер': 'Мастер',
      'Легенда': 'Легенда'
    },
    
    // NFT components
    'nft.mint': 'Создать NFT',
    'nft.gallery': 'NFT Галерея',
    'nft.no_nfts': 'NFT не найдены',
    'nft.connect_wallet': 'Подключите кошелек для создания NFT',
    'nft.wallet': 'Кошелек:',
    'nft.network': 'Сеть:',
    'nft.name': 'Название NFT',
    'nft.name_placeholder': 'Мой уникальный NFT',
    'nft.name_required': 'Введите название NFT',
    'nft.description': 'Описание',
    'nft.description_placeholder': 'Описание вашего NFT...',
    'nft.description_required': 'Введите описание NFT',
    'nft.uri': 'URI метаданных',
    'nft.uri_placeholder': 'https://example.com/metadata.json',
    'nft.uri_required': 'Введите URI метаданных',
    'nft.upload_file': 'Или загрузите файл',
    'nft.upload': 'Загрузить',
    'nft.create_via_wallet': 'Создать NFT через кошелек',
    'nft.royalty_note': '* Роялти: 5% от продаж',
    'nft.connect_first': 'Сначала подключите кошелек!',
    'nft.success_created': 'NFT успешно создан! Hash:',
    'nft.error_creating': 'Ошибка при создании NFT:',
    'nft.unknown_error': 'Неизвестная ошибка',
    'nft.connect_to_view': 'Подключите кошелек для просмотра NFT',
    'nft.loading': 'Загрузка NFT...',
    'nft.your_nfts': 'Ваши NFT',
    'nft.refresh': 'Обновить',
    'nft.no_nfts_yet': 'У вас пока нет NFT',
    'nft.view': 'Просмотр',
    'nft.transfer': 'Передать',
    'nft.burn': 'Сжечь',
    'nft.token_id': 'Token ID:',
    'nft.collection': 'GUILAND NFT Collection',
    'nft.quantity': 'Количество:',
    'nft.wallet_no_transactions': 'Кошелек не поддерживает транзакции',
    'nft.transfer_success': 'NFT успешно передан!',
    'nft.transfer_error': 'Ошибка при передаче NFT:',
    'nft.burn_success': 'NFT успешно сожжен!',
    'nft.burn_error': 'Ошибка при сжигании NFT:',
    'nft.load_error': 'Ошибка при загрузке NFT',
    'nft.token_data_error': 'Ошибка при получении данных токена:',
    'nft.castle_description': 'Величественный замок в мире GUILAND',
    'nft.dragon_description': 'Защитник королевства GUILAND',
    'nft.sword_description': 'Легендарный меч с магическими свойствами',
    
    // Common
    'common.loading': 'Загрузка...',
    'common.error': 'Ошибка',
    'common.success': 'Успешно',
    'common.required': 'обязательно',
    'common.confirm': 'Подтвердить',
    'common.test': 'Тест',
    'common.normal_mode': 'Обычный режим',
    'common.cancel': 'Отмена',
    'common.save': 'Сохранить',
    'common.delete': 'Удалить',
    'common.edit': 'Редактировать',
    'common.view': 'Просмотр',
    'common.back': 'Назад',
    'common.next': 'Далее',
    'common.previous': 'Предыдущий',
    'common.close': 'Закрыть',
    'common.open': 'Открыть',
    'common.search': 'Поиск',
    'common.filter': 'Фильтр',
    'common.sort': 'Сортировка',
    'common.refresh': 'Обновить',
    'common.download': 'Скачать',
    'common.upload': 'Загрузить',
    'common.export': 'Экспорт',
    'common.import': 'Импорт',
    'common.settings': 'Настройки',
    'common.help': 'Помощь',
    'common.about': 'О нас',
    'common.contact': 'Контакты',
    'common.privacy': 'Конфиденциальность',
    'common.terms': 'Условия',
    'common.language': 'Язык',
    'common.install': 'Установите',
    'common.wallet': 'кошелек',
    'common.and': 'и',
    'common.page': 'страницу',
    'common.coming_soon': 'Скоро',
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    // Загружаем язык из localStorage при инициализации
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'ru')) {
      setLanguageState(savedLanguage);
    } else {
      // По умолчанию английский язык
      setLanguageState('en');
      localStorage.setItem('language', 'en');
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    const currentTranslations = translations[language] as any;
    return currentTranslations[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
} 